### ISSUE TITLE
Change OpenStreetMap + Leaflet to Google Maps

### ISSUE THREAD

**Issue by lechup** [SmoglyAirMonitor/smogly-frontend#7]
Change OpenStreetMap + Leaflet to Google Maps, main reason - have one map API with address autocomplete feature like Google one: https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete-addressform

**Comment by dzienisz** [comment]
With current price changes, I dont' think that this is the best idea.

https://cloud.google.com/maps-platform/user-guide/pricing-changes/

**Comment by lechup** [comment]
Yeah, that is sad but true. I can setup OSM tile server for smogly I've already migrated couple of services to Leaflet + OSM.

The limit we have from Google we can use for places autocomplete - that is something that is still missing in OSM.

**Comment by lechup** [comment]
The thing is we should not to use main OSM tile server in production.

**Comment by lechup** [comment]
Changed to:
#12 
#11
